#!/bin/bash
echo "Compiling..."
elm make src/Main.elm --optimize --output=docs/elm.js
echo "Minifying..."
terser docs/elm.js --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=docs/elm.js
echo "Done!"
